# Generated by Django 5.0.6 on 2024-06-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0005_student_otp_alter_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forgot',
        ),
    ]
