# Generated by Django 5.0.6 on 2024-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0006_delete_forgot'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
